Task 362: test pipeline fix

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -33,21 +33,6 @@ jobs:
           cache: maven
       - name: Build with Maven
         run: mvn compile
-
-  spotbugs:
-    permissions: write-all
-    runs-on: ubuntu-latest
-
-    steps:
-      - uses: actions/checkout@v3
-        with:
-          ref: ${{ github.event.pull_request.head.sha }}
-      - name: Set up JDK 17
-        uses: actions/setup-java@v3
-        with:
-          java-version: '17'
-          distribution: 'temurin'
-          cache: maven
       - name: Build with Maven
         run: mvn -B verify spotbugs:spotbugs || true
       - name: Push SpotBugs report
@@ -56,4 +41,26 @@ jobs:
           path: 'target/spotbugsXml.xml'
       - name: Spotbugs with Maven but fail this time if spotbugs fails
         run: mvn spotbugs:check
+#  spotbugs:
+#    permissions: write-all
+#    runs-on: ubuntu-latest
+#
+#    steps:
+#      - uses: actions/checkout@v3
+#        with:
+#          ref: ${{ github.event.pull_request.head.sha }}
+#      - name: Set up JDK 17
+#        uses: actions/setup-java@v3
+#        with:
+#          java-version: '17'
+#          distribution: 'temurin'
+#          cache: maven
+#      - name: Build with Maven
+#        run: mvn -B verify spotbugs:spotbugs || true
+#      - name: Push SpotBugs report
+#        uses: jwgmeligmeyling/spotbugs-github-action@v1.2
+#        with:
+#          path: 'target/spotbugsXml.xml'
+#      - name: Spotbugs with Maven but fail this time if spotbugs fails
+#        run: mvn spotbugs:check
 
